# Referenced the following:
# - https://www.docker.com/blog/containerized-python-development-part-1/
# - https://www.docker.com/blog/containerized-python-development-part-2/
# - https://www.docker.com/blog/containerized-python-development-part-3/
# - https://fastapi.tiangolo.com/deployment/docker/

services:
  google_api:
    build: .
    command: ["uvicorn app.google:gapp --host 0.0.0.0 --port 8000 --reload"]
    restart: always
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8000:8000

  square_api:
    build: .
    command: ["uvicorn app.square:sapp --host 0.0.0.0 --port 8001 --reload"]
    restart: always
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8001:8001
